services:
    madaia33:
        image: webdevops/php-apache-dev:${DC_PHP:-8.4}
        volumes:
            - ./:/docker
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /docker
        ports:
            - "${APP_PORT:-8080}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
            APP_ENV: local
            APP_DEBUG: true
            CONTAINER_UID: 1000
            XDEBUG_CLIENT_HOST: host.docker.internal
            XDEBUG_CLIENT_PORT: 9003
            XDEBUG_DISCOVER_CLIENT_HOST: "0"
            XDEBUG_START_WITH_REQUEST: "trigger"
            XDEBUG_MODE: "debug,develop"
            PHP_MEMORY_LIMIT: 9064M
        depends_on:
            - db
        networks:
            - frontend

    madaia33-composer:
        image: webdevops/php-apache-dev:${DC_PHP:-8.4}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["composer"]
        volumes:
            - ./:/docker
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
        command: bash -c "
            rm -f composer.lock
            && composer install --no-progress"
        networks:
            - frontend

    madaia33-reformat:
        image: webdevops/php-apache-dev:${DC_PHP:-8.4}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["reformat"]
        volumes:
            - ./:/docker
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
        command: bash -c "
            ./vendor/bin/pint"
        networks:
            - frontend

    madaia33-quality:
        image: webdevops/php-apache-dev:${DC_PHP:-8.4}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["quality"]
        volumes:
            - ./:/docker
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
        command: bash -c "
            composer quality"
        networks:
            - frontend
    madaia33-npm-all:
        image: node:${DC_NODE:-24-bullseye}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["npm-all"]
        volumes:
            - ./:/docker
        ports:
            - "3000:3000"
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
        command: bash -c "
            rm -f package-lock.json
            && rm -Rf node_modules
            && npm install
            && npm run build"
        networks:
            - frontend

    madaia33-npm:
        image: node:${DC_NODE:-24-bullseye}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["npm"]
        volumes:
            - ./:/docker
        ports:
            - "3000:3000"
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
        command: bash -c "
            npm install
            && npm run build"
        networks:
            - frontend

    madaia33-migrate-all:
        image: webdevops/php-apache-dev:${DC_PHP:-8.4}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["migrate-all"]
        volumes:
            - ./:/docker
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
            APP_ENV: local
            APP_DEBUG: true
        command: bash -c "
            composer install --no-progress
            && php artisan migrate:fresh
            && php artisan db:seed"
        depends_on:
            - db
        networks:
            - frontend

    madaia33-migrate:
        image: webdevops/php-apache-dev:${DC_PHP:-8.4}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["migrate"]
        volumes:
            - ./:/docker
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
        command: bash -c "
            php artisan migrate
            && php artisan db:seed"
        depends_on:
            - db
        networks:
            - frontend
    madaia33-pentest:
        image: webdevops/php-apache-dev:${DC_PHP:-8.4}
        user: "${DC_UID:-1000}:${DC_GID:-1000}"
        profiles: ["pentest"]
        volumes:
            - ./:/docker
        working_dir: /docker
        environment:
            WEB_DOCUMENT_ROOT: /docker/public
        command: bash -c "XDEBUG_MODE='coverage' composer test"
        networks:
            - frontend

    db:
        image: mariadb:11.7
        command: --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --sql-mode=""
        environment:
            MYSQL_ROOT_PASSWORD: tormenta
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - ./dc-data/mysql:/var/lib/mysql
            - ./dc-data/mysqldumps:/mysqldumps
        networks:
            - frontend
        ports:
            - 13306:3306

    madaia33-myadmin:
        image: phpmyadmin:latest
        ports:
            - 4000:80
        environment:
            UPLOAD_LIMIT: 64M
        links:
            - db:db
        networks:
            - frontend

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - ${MAILHOG_PORT:-8025}:8025
        networks:
            - frontend

    selenium:
        image: selenium/standalone-chromium:latest
        shm_size: 2gb
        environment:
            SE_NODE_MAX_SESSIONS: 1
            SE_NODE_OVERRIDE_MAX_SESSIONS: true
            SE_VNC_NO_PASSWORD: 1
        ports:
            - "${SELENIUM_PORT:-4444}:4444"
            - "${SELENIUM_NOVNC_PORT:-7900}:7900"
        networks:
            - frontend

networks:
    frontend: null
